---
- hosts: all
  tasks:
    - include_vars: secret_vars.yml
    - name: update hostname
      sudo: true
      hostname:
        name="{{ inventory_hostname }}"

    - name: update /etc/hosts
      sudo: true
      lineinfile:
        line="127.0.1.1	{{ inventory_hostname }}"
        regexp="127.0.1.1	.*"
        dest=/etc/hosts

    - name: install packages
      sudo: true
      apt:
        name={{ item }}
        state=present
        update_cache=true
      with_items:
        - libavformat53
        - gfortran
        - iw
        - libatlas-base-dev
        - libblas-dev
        - liblapack-dev
        - libopencv-dev
        - libzmq-dev
        - python-dev
        - python-setuptools
        - supervisor
        - tk8.5-dev
        - tcl8.5-dev
        - unclutter
        - wpasupplicant
        - wireless-tools

    - name: remove packages
      sudo: true
      apt:
        name={{ item }}
        state=absent
        update_cache=true
      with_items:
        - python-numpy
        - python-opencv
        - python-zmq

    # Remove Ubuntu pip, it's too old
    - apt: name=python-pip state=absent
      sudo: true

    # easy_install pip
    - easy_install: name=pip
      sudo: true

    - name: install python packages
      sudo: true
      pip:
        name={{ item }}
      with_items:
        - virtualenv

    - name: remove mirror user
      sudo: true
      user:
        name=mirror
        state=absent

    - name: update pi user
      sudo: true
      user:
        name=pi
        password="{{ mirror_password }}"
        createhome=yes
        generate_ssh_key=yes

    - name: authorize ssh key
      sudo: true
      authorized_key:
        user={{ item }}
        key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      with_items:
        - "{{ ansible_user_id }}"

    - name: fix autologin
      sudo: true
      lineinfile:
        regexp="^autologin-user=.?$"
        line="autologin-user=pi"
        dest=/etc/lightdm/lightdm.conf


- hosts: all
  tasks:
    - copy:
        src=deploy_key
        dest=~/.ssh/deploy_key
        mode=0600

    - name: clone source
      git:
        repo=git@github.com:chachi/MirrorMirror
        dest=~/MirrorMirror
        accept_hostkey=yes
        key_file=~/.ssh/deploy_key
        force=yes
        update=yes
        version=master

    - name: install numpy
      pip:
        name={{ item.key }}
        version={{ item.value }}
        virtualenv=~/MirrorMirror/venv/
      with_dict:
        numpy: 1.8.1
        Cython: 0.20.1

    - name: install mirror requirements.txt
      pip:
        requirements=~/MirrorMirror/requirements.txt
        virtualenv=~/MirrorMirror/venv/
        extra_args="--allow-external PIL"

    - name: download opencv
      get_url:
        url=https://github.com/Nolaan/libopencv_24/releases/download/OpenCV_2.4.10.2/libopencv_2.4.10.2.deb.zip
        dest=/home/pi/libopencv_2.4.10.2.deb.zip
        sha256sum=1b8f7c25caddfa52a7cfb5979c49e17605c912f73c3fe8fa11ec1d56877ba6e1

    - name: unzip opencv libs
      unarchive:
        src=libopencv_2.4.10.2.deb.zip
        dest=/home/pi
        copy=no

    - name: dpkg opencv
      sudo: true
      shell: dpkg -i /home/pi/libopencv_2.4.10.2.deb

    - name: cp opencv
      shell: "cp /usr/local/lib/python2.7/site-packages/* ~/MirrorMirror/venv/lib/python2.7/site-packages/"

- hosts: all
  tasks:
    - include_vars: secret_vars.yml
    - name: interfaces config
      sudo: true
      template:
        src=templates/interfaces.j2
        dest=/etc/network/interfaces

    - name: wpa config
      sudo: true
      template:
        src=templates/wpa.j2
        dest=/etc/wpa_supplicant/wpa_supplicant.conf
    - name: copy videos
      copy:
        src=videos
        dest=/home/pi/

- hosts: detector
  name: start detector
  tasks:
  - name: configure supervisord
    sudo: true
    template:
      src=templates/mirror_detector.conf.j2
      dest=/etc/supervisor/conf.d/mirror_detector.conf
      owner=root group=root mode=0600

  - name: mirror_detector present
    sudo: true
    supervisorctl:
      name=mirror_detector
      state=present

  - name: restart detector
    sudo: true
    supervisorctl:
      name=mirror_detector
      state=restarted


- hosts: receivers
  name: start receiver
  tasks:
  - name: copy restart script
    copy:
      src=restart_detector.sh
      dest=/home/pi/
      owner=pi
      group=pi
      mode=ug+rwx

  - name: configure supervisord
    sudo: true
    template:
      src=templates/mirror_receiver.conf.j2
      dest=/etc/supervisor/conf.d/mirror_receiver.conf
      owner=root group=root mode=0600

  - name: mirror_receiver present
    sudo: true
    supervisorctl:
      name=mirror_receiver
      state=present

  - name: restart receiver
    sudo: true
    supervisorctl:
      name=mirror_receiver
      state=restarted
