---
- hosts: all
  tasks:
    - include_vars: secret_vars.yml
    - name: update hostname
      sudo: true
      hostname:
        name="{{ inventory_hostname }}"

    - name: install packages
      sudo: true
      apt:
        name={{ item }}
        state=present
        update_cache=true
      with_items:
        - gfortran
        - iw
        - libatlas-base-dev
        - libblas-dev
        - liblapack-dev
        - libopencv-dev
        - python-dev
        - python-setuptools
        - supervisor
        - unclutter
        - wpasupplicant
        - wireless-tools

    # Remove Ubuntu pip, it's too old
    - apt: name=python-pip state=absent
      sudo: true

    # easy_install pip
    - easy_install: name=pip
      sudo: true

    - name: install python packages
      sudo: true
      pip:
        name={{ item }}
      with_items:
        - virtualenv

    - name: add mirror user
      sudo: true
      user:
        name=mirror
        password={{ mirror_password }}
        createhome=yes
        generate_ssh_key=yes

    - name: authorize ssh key
      sudo: true
      authorized_key:
        user={{ item }}
        key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      with_items:
        - mirror
        - "{{ ansible_user_id }}"

    - name: fix autologin
      lineinfile:
        regexp="^autologin-user=.?$"
        line="autologin-user=mirror"
        dest=/etc/lightdm/lightdm.conf


- hosts: all
  remote_user: mirror
  tasks:
    - copy:
        src=deploy_key
        dest=~/.ssh/deploy_key
        mode=0600

    - name: clone source
      git:
        repo=git@github.com:chachi/MirrorMirror
        dest=~/MirrorMirror
        accept_hostkey=yes
        key_file=~/.ssh/deploy_key

    - name: install numpy
      pip:
        name={{ item.key }}
        version={{ item.value }}
        virtualenv=~/MirrorMirror/venv/
      with_dict:
        numpy: 1.8.1
        Cython: 0.20.1

    - name: install mirror requirements.txt
      pip:
        requirements=~/MirrorMirror/requirements.txt
        virtualenv=~/MirrorMirror/venv/
        extra_args="--allow-external PIL"

- hosts: all
  vars:
    wifi_static_ip: 192.168.1.1 # Default, should be overriden by host var.
  tasks:
    - name: interfaces config
      sudo: true
      template:
        src=interfaces_template
        dest=/etc/network/interfaces

    - name: wpa config
      sudo: true
      template:
        src=wpa_template
        dest=/etc/wpa_supplicant/wpa_supplicant.conf

- hosts: detector
  remote_user: mirror
  name: start detector
  tasks:
  - name: configure supervisord
    sudo: true
    template:
      src=templates/mirror_detector.conf.j2
      dest=/etc/supervisor/conf.d/mirror_detector.conf
      owner=root group=root mode=0600
    notify:
      - restart detector
  handlers:
    - name: restart apache
      sudo: true
      supervisorctl:
        name=mirror_detector
        state=restarted


- hosts: all
  remote_user: mirror
  name: start receiver
  tasks:
  - name: configure supervisord
    sudo: true
    template:
      src=templates/mirror_receiver.conf.j2
      dest=/etc/supervisor/conf.d/mirror_receiver.conf
      owner=root group=root mode=0600
    notify:
      - restart receiver
  handlers:
    - name: restart apache
      sudo: true
      supervisorctl:
        name=mirror_receiver
        state=restarted
